'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s??'').replace(/_x000D_/gi,' ').replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ');
const pad4=v=>{let s=clean(v);if(/^\d+(\.0+)?$/.test(s))s=String(parseInt(s,10));return s?s.padStart(4,'0'):''};
const coll=new Intl.Collator('de',{sensitivity:'base',numeric:true}), STORE='onepress-tree-web-v1';
let state={nextId:1000,assets:[],activeId:null,selected:null,expanded:new Set(),dirty:false};
const newid=()=>String(state.nextId++).padStart(4,'0'), asset=()=>state.assets.find(a=>a.id===state.activeId), key=(e1,e2)=>e1+'|'+e2;
const bucket=(a,e1,e2,create=false)=>{a.custom??={};const k=key(e1,e2);if(create&&!a.custom[k])a.custom[k]=[];return a.custom[k]||[]};
const sortNodes=ns=>{ns.sort((a,b)=>coll.compare(a.text,b.text));ns.forEach(n=>sortNodes(n.children||[]));return ns};
const countNodes=ns=>ns.reduce((s,n)=>s+1+countNodes(n.children||[]),0);
function serial(){return {version:1,nextId:state.nextId,assets:state.assets,activeId:state.activeId}}
function dirty(){state.dirty=true;try{localStorage.setItem(STORE,JSON.stringify(serial()))}catch{};renderStatus()}
function init(){try{const p=JSON.parse(localStorage.getItem(STORE)||'null');if(p?.assets){state.nextId=p.nextId||1000;state.assets=p.assets;state.activeId=p.activeId||p.assets[0]?.id}}catch{}if(!state.assets.length)addAsset('Anlage 1',false);wire();render()}
function addAsset(name,mark=true){const a={id:'A'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),name:clean(name)||'Anlage',custom:{}};state.assets.push(a);state.activeId=a.id;if(mark)dirty();return a}
function render(){renderAssets();renderTree();renderDetails();renderStatus()}
function renderAssets(){const box=$('#assetList');box.innerHTML='';state.assets.forEach(a=>{const d=document.createElement('div');d.className='asset'+(a.id===state.activeId?' active':'');d.innerHTML=`<span class="asset-name">${esc(a.name)}</span><span class="badge">${Object.values(a.custom||{}).reduce((s,n)=>s+countNodes(n),0)}</span>`;d.onclick=()=>{state.activeId=a.id;state.selected=null;state.expanded.clear();render()};box.appendChild(d)});$('#assetCount').textContent=state.assets.length}
function master1(id){return MASTER.find(x=>x.id===id)}
function master2(e1,e2){return master1(e1)?.children.find(x=>x.id===e2)}
function skey(r){return [r.level,r.e1,r.e2||'',...(r.ids||[])].join('>')}
function resolveCustom(a,e1,e2,ids){let ns=bucket(a,e1,e2),n=null;for(const id of ids){n=ns.find(x=>x.id===id);if(!n)return null;ns=n.children||[]}return n}
function childrenOf(a,r){if(r.level===1)return master1(r.e1).children.map(x=>({level:2,e1:r.e1,e2:x.id,id:x.id,text:x.text,master:true,ids:[]}));if(r.level===2)return sortNodes(bucket(a,r.e1,r.e2)).map(n=>({level:3,e1:r.e1,e2:r.e2,id:n.id,text:n.text,master:false,ids:[n.id],node:n}));const n=resolveCustom(a,r.e1,r.e2,r.ids);return sortNodes(n?.children||[]).map(c=>({level:r.level+1,e1:r.e1,e2:r.e2,id:c.id,text:c.text,master:false,ids:[...r.ids,c.id],node:c}))}
function hasKids(a,r){if(r.level===1)return master1(r.e1).children.length>0;if(r.level===2)return bucket(a,r.e1,r.e2).length>0;return (r.node?.children||[]).length>0}
function rows(){const a=asset(),out=[];if(!a)return out;const walk=r=>{r.k=skey(r);out.push(r);if(state.expanded.has(r.k))childrenOf(a,r).forEach(walk)};MASTER.forEach(m=>walk({level:1,e1:m.id,e2:'',id:m.id,text:m.text,master:true,ids:[]}));return out}
function renderTree(){const a=asset(),body=$('#treeBody');body.innerHTML='';$('#treeTitle').textContent=a?'Stillstandsbaum · '+a.name:'Stillstandsbaum';if(!a)return;const q=norm($('#search').value);let shown=0;for(const r of rows()){if(q&&!norm(r.id+' '+r.text).includes(q)&&!r.master)continue;shown++;const tr=document.createElement('tr');tr.className=(r.master?'master ':'')+(state.selected===r.k?'selected':'');const kids=hasKids(a,r),open=state.expanded.has(r.k);tr.innerHTML=`<td>${esc(r.id)}</td><td><span class="level-pill">Ebene ${r.level}</span></td><td><div class="cell-name"><span class="indent" style="width:${(r.level-1)*18}px"></span><span class="twisty">${kids?(open?'▾':'▸'):''}</span><span class="node-text">${esc(r.text)}</span></div></td><td>${r.master?'<span class="lock">🔒 Master</span>':'Standort'}</td>`;tr.onclick=e=>{if(e.target.classList.contains('twisty')&&kids){open?state.expanded.delete(r.k):state.expanded.add(r.k);renderTree();return}state.selected=r.k;renderTree();renderDetails()};tr.ondblclick=()=>{if(kids){open?state.expanded.delete(r.k):state.expanded.add(r.k);renderTree()}};body.appendChild(tr)}$('#rowCount').textContent=shown+' Zeilen'}
function selected(){if(!state.selected)return null;const p=state.selected.split('>'),level=+p[0],e1=p[1],e2=p[2],ids=p.slice(3);if(level===1){const m=master1(e1);return {...m,level,e1,e2:'',ids,master:true}}if(level===2){const m=master2(e1,e2);return {...m,level,e1,e2,ids,master:true}}const n=resolveCustom(asset(),e1,e2,ids);return n?{...n,level,e1,e2,ids,master:false,node:n}:null}
function pathText(s){const a=[];const m1=master1(s.e1);if(m1)a.push(m1.id+' · '+m1.text);if(s.e2){const m2=master2(s.e1,s.e2);if(m2)a.push(m2.id+' · '+m2.text)}if(s.level>=3){let ns=bucket(asset(),s.e1,s.e2);for(const id of s.ids){const n=ns.find(x=>x.id===id);if(!n)break;a.push(n.id+' · '+n.text);ns=n.children||[]}}return a.join(' › ')}
function renderDetails(){const b=$('#details'),s=selected();if(!s){b.innerHTML='Wähle einen Knoten aus.';return}if(s.master){b.innerHTML=`<div class="field"><label>Nummer</label><input disabled value="${esc(s.id)}"></div><div class="field"><label>Ebene</label><input disabled value="${s.level}"></div><div class="field"><label>Beschreibung</label><textarea disabled>${esc(s.text)}</textarea></div><div class="field"><label>Pfad</label><div class="path">${esc(pathText(s))}</div></div><div class="note">Ebene 1 und 2 sind unveränderliche Masterdaten.</div>`;return}b.innerHTML=`<div class="field"><label>Nummer</label><input disabled value="${esc(s.id)}"></div><div class="field"><label>Ebene</label><input disabled value="${s.level}"></div><div class="field"><label>Beschreibung</label><textarea id="editText">${esc(s.text)}</textarea></div><div class="field"><label>Pfad</label><div class="path">${esc(pathText(s))}</div></div><div class="detail-actions"><button class="primary" id="applyEdit">Übernehmen</button><button id="copyDetail">Teilbaum kopieren</button><button class="danger" id="deleteDetail">Löschen</button></div>`;$('#applyEdit').onclick=()=>{const t=clean($('#editText').value);if(!t)return alert('Beschreibung fehlt.');s.node.text=t;sortNodes(bucket(asset(),s.e1,s.e2));dirty();render()};$('#copyDetail').onclick=copyTree;$('#deleteDetail').onclick=deleteNode}
function addChild(text){const s=selected(),a=asset();if(!s)return {ok:false,msg:'Bitte einen Parent-Knoten auswählen.'};if(s.level===1)return {ok:false,msg:'Ebene 3 kann nur unter Ebene 2 angelegt werden.'};if(s.level>=7)return {ok:false,msg:'Ebene 7 ist die maximale Ebene.'};let ns=s.level===2?bucket(a,s.e1,s.e2,true):(s.node.children??=[]);const t=clean(text);if(!t)return {ok:false,msg:'Beschreibung fehlt.'};if(ns.some(n=>norm(n.text)===norm(t)))return {ok:false,msg:'Ein gleichnamiger Knoten existiert bereits.'};ns.push({id:newid(),text:t,children:[]});sortNodes(ns);state.expanded.add(state.selected);dirty();return {ok:true}}
function promptChild(){const s=selected();if(!s)return alert('Bitte Parent auswählen.');const t=prompt('Beschreibung für Ebene '+(s.level+1)+':');if(t===null)return;const r=addChild(t);if(!r.ok)alert(r.msg);render()}
function addMany(){const s=selected();if(!s||s.level===1||s.level>=7)return alert('Mehrfachanlage ist nur unter Ebene 2 bis 6 möglich.');modal('Mehrere Einträge für Ebene '+(s.level+1),'<div class="note">Eine Beschreibung pro Zeile.</div><textarea id="manyText"></textarea>',[{t:'Abbrechen'},{t:'Einträge übernehmen',p:1,a:()=>{const vals=[...new Set($('#manyText').value.split(/\r?\n/).map(clean).filter(Boolean))];let n=0;vals.forEach(x=>{if(addChild(x).ok)n++});closeModal();render();alert(n+' Einträge angelegt.')}}]);setTimeout(()=>$('#manyText').focus(),20)}
function deleteNode(){const s=selected();if(!s)return;if(s.master)return alert('Ebene 1 und 2 können nicht gelöscht werden.');if(!confirm('Knoten inklusive Unterknoten löschen?'))return;let ns;if(s.level===3)ns=bucket(asset(),s.e1,s.e2,true);else{const p=resolveCustom(asset(),s.e1,s.e2,s.ids.slice(0,-1));ns=p?.children||[]}const i=ns.findIndex(n=>n.id===s.id);if(i>=0)ns.splice(i,1);state.selected=null;dirty();render()}
function cloneNode(n){return {id:newid(),text:n.text,children:(n.children||[]).map(cloneNode)}}
function merge(target,sources){for(const s of sources){let t=target.find(x=>norm(x.text)===norm(s.text));if(!t){t=cloneNode(s);target.push(t)}else merge(t.children??=[],s.children||[])}sortNodes(target)}
function copyTree(){const s=selected();if(!s||s.master)return alert('Bitte einen Standort-Knoten auswählen.');const ao=state.assets.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join(''),mo=MASTER.flatMap(m=>m.children.map(c=>`<option value="${m.id}|${c.id}">${m.id}/${c.id} · ${esc(m.text)} / ${esc(c.text)}</option>`)).join('');modal('Teilbaum kopieren',`<div class="field"><label>Zielanlage</label><select id="copyAsset">${ao}</select></div><div class="field"><label>Ziel unter Ebene 2</label><select id="copyMaster">${mo}</select></div>`,[{t:'Abbrechen'},{t:'Kopieren',p:1,a:()=>{const ta=state.assets.find(a=>a.id===$('#copyAsset').value),[e1,e2]=$('#copyMaster').value.split('|');merge(bucket(ta,e1,e2,true),[s.node]);dirty();closeModal();render()}}])}
function csvRows(a){const out=[];for(const m1 of MASTER){if(!m1.children.length){out.push([m1.id,'','','','','','']);continue}for(const m2 of m1.children){const roots=sortNodes(bucket(a,m1.id,m2.id));if(!roots.length){out.push([m1.id,m2.id,'','','','','']);continue}const walk=(n,p)=>{const q=[...p,n.text];if(!(n.children||[]).length){const row=[m1.id,m2.id,...q];while(row.length<7)row.push('');out.push(row.slice(0,7))}else sortNodes(n.children).forEach(c=>walk(c,q))};roots.forEach(r=>walk(r,[]))}}return out}
function validate(a){const errors=[];let ids=new Set(),custom=0;const walk=(ns,l)=>ns.forEach(n=>{custom++;if(ids.has(n.id))errors.push('Doppelte Nummer '+n.id);ids.add(n.id);if(!clean(n.text))errors.push('Leere Beschreibung auf Ebene '+l);if(l>7)errors.push('Baumtiefe > 7');walk(n.children||[],l+1)});Object.values(a.custom||{}).forEach(ns=>walk(ns,3));const rows=csvRows(a);if(rows.length>10000)errors.push('Mehr als 10.000 CSV-Zeilen.');return {errors,custom,rows}}
function renderStatus(){const a=asset();if(!a)return;const v=validate(a);$('#validity').textContent=v.errors.length?'✕ '+v.errors.length+' Fehler':'✓ Baum valide';$('#validity').className=v.errors.length?'bad':'good';$('#nodeCount').textContent=v.custom+' Standort-Knoten';$('#csvCount').textContent=v.rows.length+' CSV-Zeilen';$('#saveState').textContent=state.dirty?'Ungespeicherte Änderungen':'Auto-Sicherung aktiv'}
function download(data,name,type){const b=data instanceof Blob?data:new Blob([data],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function safe(s){return clean(s).replace(/[<>:"/\\|?*]+/g,'_').replace(/\s+/g,'_')||'Anlage'}
function exportCsv(){const a=asset();if(!a)return;const v=validate(a);if(v.errors.length)return alert(v.errors.join('\n'));const rows=[['Ebene 1','Ebene 2','Ebene 3','Ebene 4','Ebene 5','Ebene 6','Ebene 7'],...v.rows],cell=v=>/[;"\r\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;download('\ufeff'+rows.map(r=>r.map(x=>cell(String(x))).join(';')).join('\r\n'),safe(a.name)+'.csv','text/csv;charset=utf-8')}
function saveProject(){download(JSON.stringify({...serial(),savedAt:new Date().toISOString()},null,2),'OnePress_Stillstandsbaum.onepress-tree','application/json');state.dirty=false;renderStatus()}
function loadProject(f){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);state.nextId=p.nextId||1000;state.assets=p.assets||[];state.activeId=p.activeId||state.assets[0]?.id;state.selected=null;state.expanded.clear();state.dirty=false;dirty();state.dirty=false;render()}catch(e){alert('Projektdatei ungültig: '+e.message)}};r.readAsText(f)}
function expandAll(){const a=asset();if(!a)return;const walk=r=>{state.expanded.add(skey(r));childrenOf(a,r).forEach(walk)};MASTER.forEach(m=>walk({level:1,e1:m.id,e2:'',id:m.id,text:m.text,master:true,ids:[]}));renderTree()}
function detect(ws,name){const data=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});let best=null;for(let r=0;r<Math.min(35,data.length);r++){const h=data[r].map(norm),map={},filters=[];h.forEach((x,i)=>{if(/ebene 1 sortierung|ebene 1 nummer|ebbene 1 sortierung/.test(x))map.e1id=i;else if(/ebene 1 text|ebbene 1 text/.test(x))map.e1text=i;else if(/^ebene 2$|^ebbene 2$|ebene 2 nummer/.test(x))map.e2id=i;else if(/ebene 2 text|ebbene 2 text/.test(x))map.e2text=i;else{const m=x.match(/(?:ebene|ebbene) ([3-7])/);if(m)map['e'+m[1]]=i;else if(/^s\s*\d/.test(x)||/^s\d/.test(x))filters.push({i,label:clean(data[r][i])})}});if(map.e1text==null){const i=h.findIndex(x=>/^ebene 1$|^ebbene 1$/.test(x));if(i>=0)map.e1text=i}const score=[3,4,5,6,7].filter(n=>map['e'+n]!=null).length+(map.e1id!=null||map.e1text!=null?2:0)+(map.e2id!=null||map.e2text!=null?2:0);if(score>=5&&(!best||score>best.score))best={name,data,row:r,map,filters,score}}return best}
function resolveMaster(e1id,e1text,e2id,e2text){let m1=e1id?MASTER.find(x=>x.id===pad4(e1id)):null;if(!m1&&e1text)m1=MASTER.find(x=>norm(x.text)===norm(e1text));if(!m1)return null;let m2=e2id?m1.children.find(x=>x.id===pad4(e2id)):null;if(!m2&&e2text)m2=m1.children.find(x=>norm(x.text)===norm(e2text));return m2?{e1:m1.id,e2:m2.id}:null}
function preview(d,filter=null){const out=[],errors=[];for(let r=d.row+1;r<d.data.length;r++){const row=d.data[r];if(!row.some(x=>clean(x)))continue;if(filter!=null&&norm(row[filter])!=='x')continue;if(norm(row.join(' ')).includes('ausblenden'))continue;const m=d.map,mm=resolveMaster(m.e1id!=null?row[m.e1id]:'',m.e1text!=null?row[m.e1text]:'',m.e2id!=null?row[m.e2id]:'',m.e2text!=null?row[m.e2text]:'');const lv=[3,4,5,6,7].map(n=>m['e'+n]!=null?clean(row[m['e'+n]]):'');if(!lv.some(Boolean))continue;if(!mm){errors.push('Zeile '+(r+1)+': Ebene 1/2 nicht zuordenbar');continue}let blank=false,gap=false;lv.forEach(x=>{if(!x)blank=true;else if(blank)gap=true});if(gap){errors.push('Zeile '+(r+1)+': Hierarchielücke');continue}out.push({...mm,levels:lv.filter(Boolean)})}const u=new Map();out.forEach(x=>u.set([x.e1,x.e2,...x.levels.map(norm)].join('|'),x));return {rows:[...u.values()],errors}}
function importRows(a,rows,replace){if(replace)a.custom={};let n=0;rows.forEach(r=>{let ns=bucket(a,r.e1,r.e2,true);r.levels.forEach(t=>{let x=ns.find(n=>norm(n.text)===norm(t));if(!x){x={id:newid(),text:t,children:[]};ns.push(x);n++}ns=x.children??=[]})});Object.values(a.custom).forEach(sortNodes);return n}
function excelFile(f){if(typeof XLSX==='undefined')return alert('Excel-Bibliothek konnte nicht geladen werden.');const fr=new FileReader();fr.onload=()=>{try{const wb=XLSX.read(fr.result,{type:'array'}),ds=wb.SheetNames.map(n=>detect(wb.Sheets[n],n)).filter(Boolean);if(!ds.length)throw Error('Kein kompatibles Arbeitsblatt erkannt.');let opts=ds.map((d,i)=>`<option value="${i}">${esc(d.name)}</option>`).join(''),assets=state.assets.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');modal('Excel importieren',`<div class="field"><label>Arbeitsblatt</label><select id="impSheet">${opts}</select></div><div class="field"><label>Zielanlage</label><select id="impAsset">${assets}</select></div><div class="field"><label>Anlagenfilter</label><select id="impFilter"><option value="">Kein X-Filter</option></select></div><div class="field"><label>Importmodus</label><select id="impMode"><option value="merge">Zusammenführen</option><option value="replace">E3–E7 ersetzen</option></select></div><div id="impInfo"></div>`,[{t:'Abbrechen'},{t:'Importieren',p:1,a:()=>{const d=ds[+$('#impSheet').value],fi=$('#impFilter').value===''?null:+$('#impFilter').value,p=preview(d,fi),a=state.assets.find(x=>x.id===$('#impAsset').value);if(p.errors.length&&!confirm(p.errors.length+' Konflikte überspringen?'))return;const added=importRows(a,p.rows,$('#impMode').value==='replace');state.activeId=a.id;dirty();closeModal();render();alert(p.rows.length+' Pfade verarbeitet · '+added+' neue Knoten.')}}]);const upd=()=>{const d=ds[+$('#impSheet').value],sel=$('#impFilter');sel.innerHTML='<option value="">Kein X-Filter</option>'+d.filters.map(x=>`<option value="${x.i}">${esc(x.label)}</option>`).join('');const p=preview(d,null);$('#impInfo').innerHTML=p.errors.length?`<div class="warn">${p.rows.length} Pfade · ${p.errors.length} Konflikte</div>`:`<div class="ok">${p.rows.length} eindeutige Pfade erkannt.</div>`};$('#impSheet').onchange=upd;upd()}catch(e){alert('Excel-Import fehlgeschlagen: '+e.message)}};fr.readAsArrayBuffer(f)}
function modal(title,body,buttons){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;const f=$('#modalFoot');f.innerHTML='';buttons.forEach(b=>{const x=document.createElement('button');x.textContent=b.t;if(b.p)x.className='primary';x.onclick=b.a||closeModal;f.appendChild(x)});$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function wire(){
$('#addAsset').onclick=()=>{const n=prompt('Anlagenname / Kennung:','S010');if(n!==null){addAsset(n);render()}};$('#dupAsset').onclick=()=>{const a=asset();if(!a)return;const n=prompt('Name der Kopie:',a.name+' Kopie');if(n===null)return;const b=addAsset(n,false);b.custom=JSON.parse(JSON.stringify(a.custom));const re=ns=>ns.forEach(x=>{x.id=newid();re(x.children||[])});Object.values(b.custom).forEach(re);dirty();render()};$('#renameAsset').onclick=()=>{const a=asset(),n=a&&prompt('Neuer Name:',a.name);if(n){a.name=clean(n);dirty();render()}};$('#deleteAsset').onclick=()=>{const a=asset();if(a&&confirm('Anlage '+a.name+' löschen?')){state.assets=state.assets.filter(x=>x.id!==a.id);state.activeId=state.assets[0]?.id||null;state.selected=null;dirty();render()}};
$('#addChild').onclick=promptChild;$('#addMany').onclick=addMany;$('#copyTree').onclick=copyTree;$('#deleteNode').onclick=deleteNode;$('#expandAll').onclick=expandAll;$('#collapseAll').onclick=()=>{state.expanded.clear();renderTree()};$('#search').oninput=renderTree;
$('#saveProject').onclick=saveProject;$('#openProject').onclick=()=>$('#projectFile').click();$('#newProject').onclick=()=>{if(state.dirty&&!confirm('Aktuelles Projekt verwerfen?'))return;state={nextId:1000,assets:[],activeId:null,selected:null,expanded:new Set(),dirty:false};addAsset('Anlage 1',false);dirty();render()};$('#exportCsv').onclick=exportCsv;$('#importExcel').onclick=()=>$('#excelFile').click();
$('#projectFile').onchange=e=>{if(e.target.files[0])loadProject(e.target.files[0]);e.target.value=''};$('#excelFile').onchange=e=>{if(e.target.files[0])excelFile(e.target.files[0]);e.target.value=''};$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')closeModal();if(e.ctrlKey&&e.key==='Enter'&&$('#modal').classList.contains('show'))$('#modalFoot .primary')?.click()})}
init();
